pipeline:
  # Library does not need to build
  #build:
  #  image: golang:latest
  #  commands:
  #    - go get -d -t ./...
  #    - go install
  test-coverage:
    image: golang:latest
    commands:
      - go get -u github.com/mattn/goveralls
      - go get -u golang.org/x/tools/cmd/cover
      - go get -d -t ./...
      - ./contrib/ci/check-coverage drone.io
  codestyle:
    image: golang:latest
    commands:
      - ./contrib/ci/check-testfiles
      - ./contrib/ci/check-gofmt
      - go get github.com/client9/misspell/cmd/misspell
      - misspell -error .
  test-race:
    image: golang:latest
    commands:
      - go get -d -t ./...
      - go test -race ./...
