language: go
go:
  - tip
install:
  - go get -t codeberg.org/genofire/golang-lib/...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/client9/misspell/cmd/misspell
script:
  - cd $GOPATH/src/codeberg.org/genofire/golang-lib
  # - go install # Library does not need to build
  - ./contrib/ci/check-coverage travis-ci
  - ./contrib/ci/check-testfiles
  - ./contrib/ci/check-gofmt
  - misspell -error .
  - go test -race ./...
